spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
  datasource:
    url: jdbc:mysql://db_dummy_host:db_dummy_port/db_dummy_name
    username: db_dummy_username
    password: db_dummy_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        ddl-auto: validate エンティティとデータベーススキーマが一致しているか検証
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mybatis:
    type-aliases-package: importApp.Entity
    mapper-locations: classpath:importApp/mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
  spring:
    flyway:
      enabled: false
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

jwt:
  secret: dummy_jwt_secret

analyzer:
  api:
    base-url: "http://localhost:5000/api/v1"

gemini:
  api:
    key: dummy_gemini_key
    url: "https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent"

# ログ設定
logging:
  level:
    importApp: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    com.mysql: WARN
    root: INFO
  file:
    path: logs
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30