spring:
  datasource:
    url: jdbc:mysql://localhost:3306/importApp
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, email, profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email
  server:
    # すべてのネットワークインターフェースでリッスン：デバッグ用
    address: 0.0.0.0
    port: 8080
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
  flyway:
    enable: true
    location: classpath:db/migration
    baseline-on-migration: true
    baseline-version: 1
  mybatis:
    type-aliases-package: importApp.Entity
    mapper-locations: classpath:importApp/mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true

jwt:
  secret: your_local_jwt_secret_change_in_production

app:
  base-url: "http://localhost:8080"
  frontend-url: "http://localhost:5173"
  mobile-callback-url: "sbmapp://auth/callback"

analyzer:
  api:
    base-url: "http://localhost:5000/api/v1"

gemini:
  api:
    key: dummy_gemini_key
    url: "https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent"

ai:
  limits:
    enabled: ${AI_LIMITS_ENABLED:true}
    debug-mode: ${AI_LIMITS_DEBUG_MODE:false}  # 本番モードに変更
    default-daily: ${AI_LIMITS_DEFAULT_DAILY:5}
    default-monthly: ${AI_LIMITS_DEFAULT_MONTHLY:50}
    debug-user-ids: ${AI_LIMITS_DEBUG_USER_IDS:}  # 空に設定

storage:
  upload-dir: uploads/profiles
  base-url: http://localhost:8080/uploads/profiles

logging:
  level:
    importApp: DEBUG
    org.springframework.security: DEBUG