spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/importApp
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enable: true
    location: classpath:db/migration
    baseline-on-migration: true
    baseline-version: 1

  mybatis:
    type-aliases-package: importApp.Entity
    mapper-locations: classpath:importApp/mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true

jwt:
  secret: yourSecretKeyHere

analyzer:
  api:
    base-url: "http://localhost:5000/api/v1"
